---
output:
  word_document: default
---

**WSN 2019 POSTER LIST**

This MS Word document was  created with RMarkdown using a report generated in CVENT


 Attribute     | Meta-Data
---------------|-------------------------------------------|
 Script        | WSN2019_poster_list.Rmd                   |
 Author        | Matt Whalen & Mairin Deith     |
 Date          | 21 October, 2019                          |



**POSTER TITLES**

```{r, results='asis', echo=FALSE}
# print header
#     cat(paste0("``*`` ", "indicates presenting author", "  \n",
# "&dagger; indicates eligibility for Best Student Paper/Poster Award", "  \n","\n"))
```
          
     
```{r, results='asis', echo=FALSE, warning=F}
# load data.table package to index affiliations
library(data.table)
# read data, use UTF-8 encoding to preserve the special characters
d <- read.csv( "../Data Files/WSN2019_registrants_TalksPosters_TalkTableVersion.csv", 1, encoding="UTF-8", stringsAsFactors=F )
# only select the posters
d <- d[d$presentation.type == 'Yes, I would like to present a poster',]
# sort alphabetically by first author
d <- d[order(d$author.1),]
set.seed(1234)
### Sort posters into two equal sessions and randomly assign numbers to posters in each session
# d$poster.session <- NaN
# session.1 <- sample(1:nrow(d),ceiling(nrow(d)/2))
# d$poster.session[session.1] <- 1
# d$poster.session[-session.1] <- 2

### Choice of either continuous numbering (1:n posters) or numbering in two sessions (1:n/2 for each session)
d$poster.number <- sample(1:nrow(d))
### 2-session numbering
# d$poster.number[session.1] <- sample(1:length(session.1))
# d$poster.number[-session.1] <- sample(1:(nrow(d)-length(session.1)))

d <- d[with(d, order(poster.number)),]
### 2-session numbering
# d <- d[with(d, order(poster.session, poster.number)),]

# replace all occurrences of special characters with HTML entities
d$title <- eval( parse( text=gsub("<U\\+([0-9]*)>","&#x\\1\\;", deparse(d$title)) ))
d$abstract <- eval( parse( text=gsub("<U\\+([0-9]*)>","&#x\\1\\;", deparse(d$abstract)) )) 

# make titles uppercase
d$title <- gsub("(\\w*)", "\\U\\1", d$title, perl=TRUE)
# make all text in html characters lowercase - only one case, but need a better solution to all us to ignore html characters when making things uppercase
d$title <- gsub( "(&\\w+;)", "\\L\\1", d$title, perl=TRUE)

# save column names for finding all authors and affiliations
column_names <- names(d)
# set basenames for finding author and affiliation columns (e.g. author.1, affiliation.15)
basenames <- c("author", "affiliation")

# There are some NAs in the column "judged" we will mark as "No" to avoid problems with logical statements in for loop below
d$student.judging.category[is.na(d$student.judging.category)] <- ""
# if presenter is student who wants to be judged, use a dagger to mark their name
d$dagger <- ifelse( d$student.judging.category != "","&dagger;", "")

# There are also some NAs for presenter number. Make these all 1
d$presenter.number <- "1"
# Assume that if there is no author 1, the author is the registrant
d$author.1[d$author.1==""] <- d$Full.Name[d$author.1==""]

# for loop to look at each row of the spreadsheet, compile all authors and match with their affiliations, make affiliation footnotes, and concatenate and print the abstracgt
#for(s in unique(d$poster.session)){
#for(s in unique(d$poster.session)){
#  cat(paste0("**Session ",s,"**", "  \n \n"))
cat(paste0("``*`` ", "indicates presenting author", "  \n", 
           "&dagger; indicates eligibility for Best Student Paper/Poster Award", "  \n","\n"))
#  d.tmp <- d[d$poster.session==s,]
d.tmp <- d



for(i in 1:nrow(d.tmp)){
  footnoted_lists <- lapply(basenames, function(basename) {
    auths <-d.tmp[i,grep(paste0(basename, "\\.[0-9]"), column_names)]
    auths <- auths[!is.na(auths)] # trim empty
    auths <- auths[auths!=""]
        # Ensure authors' names are in Title Case
    ### WARNING: Fails for names like McCallum, O'Dodd, etc. with two capital letters
    # replacement.phrase <- "\\b([[:alpha:]])([[:alpha:]]+)"
    # gsub(replacement.phrase, "\\U\\1\\L\\2", auths, perl=T)
  }
  )
  for(n in 1:length(footnoted_lists[[1]])){
        auth.tmp <- footnoted_lists[[1]][n]
        last.tmp <- strsplit(auth.tmp, split=",", fixed=T)[[1]][1]
        first.tmp <- strsplit(auth.tmp, split=",", fixed=T)[[1]][2]
        # Capital letters in first.tmp
        first.split <- strsplit(first.tmp, split='')[[1]]
        first.initials <- first.split[grepl("[A-Z]",first.split)]
        first.initials <- paste(c(first.initials, ''), collapse=". ")
        # Now tie in the last name, and only the first two initials if they are there
        footnoted_lists[[1]][n] <- paste(last.tmp, substr(first.initials, start=1, stop=5), sep=", ")
    }
     dt <- data.table(matrix(unlist(footnoted_lists),ncol=2))
     dt[, idx := .GRP, by = V2]
     if(length(unique(dt$idx))==1) dt$idx <- 0
     # asertisk to mark the presenter
     dt$presenter <- ""
     dt$presenter[as.numeric(d$presenter.number[i])] <- "^``*``^"

  # paste all of the superscripts for authors, as well as asterisk for presenter
  auths <- ifelse(length(unique(dt$idx))>1, paste0(footnoted_lists[[1]], dt$presenter, collapse=", "), paste0(footnoted_lists[[1]], dt$presenter,collapse=", "))
  
  gsub(pattern=" ^``*``^","^``*``^",auths,fixed=T)
  # print everything in order with italics and bold where needed
     cat(paste0(
       #d.tmp$poster.number[i]," - ", 
       "**",d.tmp$dagger[i],auths,"**","  \n",
         d.tmp$title[i],"  \n",
     "  \n", "  \n"))
}
```

